### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by iamcco** [iamcco/coc-zi#2]
<img width="964" alt="zi-suggest" src="https://user-images.githubusercontent.com/5492542/67636928-7341dd00-f910-11e9-8418-09c805fa856a.png">
<img width="964" alt="zi-translator" src="https://user-images.githubusercontent.com/5492542/67636930-76d56400-f910-11e9-8303-8aa783903384.png">

**Comment by iamcco** [comment]
![zi](https://user-images.githubusercontent.com/5492542/67637192-dfbddb80-f912-11e9-9fdf-2985eb015602.gif)

**Comment by voldikss** [comment]
![字-order](https://user-images.githubusercontent.com/20282795/71557618-7594f480-2a83-11ea-8858-6e5f79500de1.gif)

A nice gif without the watermark😂
