### ISSUE TITLE
Regular expression or syntax kind for python multi-line docstring?

### ISSUE THREAD

**Issue by againxx** [iamcco/coc-zi#7]
Great plugin!
I am trying to use this autocompletion in python regular strings and multi-line docstrings (multiple lines begin and end with triple """)
I add following lines in coc-settings.json, and it works fine for normal strings, so I wonder if there is a easy way to come up with a pattern for multi-line docstrings in python.
```
"zi.syntaxKinds.python": [
    "StringLiteral",
],
```
Thank you!

**Comment by againxx** [comment]
I have tried `"^\\s*\\\"\\\"\\\"[\\s\\S]\\\"\\\"\\\""`, but it didn't work.

**Comment by iamcco** [comment]
It's weird, `syntaxKinds` should only works with Typescript or Javascript. `zi.syntaxKinds.python` is not a valid option. By now multi-line is not support.

**Comment by againxx** [comment]
Thank you! I may use a keybinding to manually toggle it in python files.

**Comment by againxx** [comment]
Interesting, I find it hard to dynamically toggle coc-zi after entered nvim.
May be a problem from coc? I also opened a issue in coc.nvim [#1872](https://github.com/neoclide/coc.nvim/issues/1872#issue-615080652).
